---

name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Prepare dependencies
        uses: jdx/mise-action@v2

      - name: Run tests
        run: |
          nvim --version
          make test
