---

name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Prepare dependencies
        run: |
          mkdir -p _neovim
          curl -sL https://github.com/neovim/neovim/releases/download/v0.9.0/nvim-linux64.tar.gz | tar xzf - --strip-components=1 -C "${PWD}/_neovim"
          cargo install cargo-nextest --locked
      - name: Run tests
        run: |
          export PATH="${PWD}/_neovim/bin:${PATH}"
          nvim --version
          cargo --version
          cargo nextest --version
          make test
